name: Trigger auto deployment for prompt-practice-range

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/prompt-practice-range-AutoDeployTrigger-f6028c1d-552e-4a1a-a23c-f351201ce999.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PROMPTPRACTICERANGE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PROMPTPRACTICERANGE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PROMPTPRACTICERANGE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: neurascanacr2026.azurecr.io
          registryUsername: ${{ secrets.PROMPTPRACTICERANGE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PROMPTPRACTICERANGE_REGISTRY_PASSWORD }}
          containerAppName: prompt-practice-range
          resourceGroup: prompt-practice-rg
          imageToBuild: neurascanacr2026.azurecr.io/prompt-practice-range:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


